# fly.toml app configuration file generated for bookbot-discord on 2023-05-22T20:57:35+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookbot-discord"
primary_region = "hkg"

[build]
  builder = "paketobuildpacks/builder:base"
